In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("../data/dataset_train.csv")

In [3]:
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
0,140690,2017-07-02 00:00,858557,C,359520,13787,4,NaN,10.0,Female,4.0,3.0,3.0,0,0
1,333291,2017-07-02 00:00,243253,C,105960,11085,5,NaN,8.0,Female,2.0,2.0,NaN,0,0
2,129781,2017-07-02 00:00,243253,C,359520,13787,4,NaN,8.0,Female,2.0,2.0,NaN,0,0
3,464848,2017-07-02 00:00,1097446,I,359520,13787,3,NaN,3.0,Male,3.0,3.0,2.0,1,0
4,90569,2017-07-02 00:01,663656,C,405490,60305,3,NaN,2.0,Male,2.0,3.0,2.0,1,0

In [4]:
df.shape

(463291, 15)

In [5]:
tab_info = pd.DataFrame(df.dtypes).T.rename(index={0:'column type'})
tab_info = pd.concat([tab_info, pd.DataFrame(df.isnull().sum()).T.rename(index={0:'null values (nb)'})])

tab_info = pd.concat([tab_info, pd.DataFrame(df.isnull().sum()/df.shape[0]*100).T.rename(index={0:'null values (%)'})])

tab_info

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
column type,int64,str,int64,str,int64,int64,int64,float64,float64,str,float64,float64,float64,int64,int64
null values (nb),0,0,0,0,0,0,0,365854,18243,18243,18243,18243,125129,0,0
null values (%),0.0,0.0,0.0,0.0,0.0,0.0,0.0,78.96851,3.937698,3.937698,3.937698,3.937698,27.008727,0.0,0.0

In [6]:
df.drop(labels='product_category_2', axis=1, inplace=True)

In [7]:
sum(df['is_click'] == 1)

31331

In [8]:

num_missing = df['city_development_index'].isnull().sum()
if num_missing > 0:
    missing_indices = df['city_development_index'].isnull()
    num_missing_values = num_missing
    replace_values = np.random.choice([1, 2, 3,4], size=num_missing_values, p=[0.25, 0.25,0.25,0.25])
    df['city_development_index'][missing_indices] = replace_values

In [9]:
df.isna().sum()

session_id                     0
DateTime                       0
user_id                        0
product                        0
campaign_id                    0
webpage_id                     0
product_category_1             0
user_group_id              18243
gender                     18243
age_level                  18243
user_depth                 18243
city_development_index    125129
var_1                          0
is_click                       0
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.isna().sum()

session_id                0
DateTime                  0
user_id                   0
product                   0
campaign_id               0
webpage_id                0
product_category_1        0
user_group_id             0
gender                    0
age_level                 0
user_depth                0
city_development_index    0
var_1                     0
is_click                  0
dtype: int64

In [12]:
sum(df['is_click'] == 1)

22849

In [14]:
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
0,140690,2017-07-02 00:00,858557,C,359520,13787,4,10.0,Female,4.0,3.0,3.0,0,0
3,464848,2017-07-02 00:00,1097446,I,359520,13787,3,3.0,Male,3.0,3.0,2.0,1,0
4,90569,2017-07-02 00:01,663656,C,405490,60305,3,2.0,Male,2.0,3.0,2.0,1,0
6,17583,2017-07-02 00:01,1091463,F,405490,60305,3,9.0,Female,3.0,3.0,4.0,0,0
7,461128,2017-07-02 00:01,469098,C,360936,13787,3,4.0,Male,4.0,3.0,4.0,0,0

In [15]:

LE = LabelEncoder()
df['gender'] = LE.fit_transform(df['gender'])
df['product'] = LE.fit_transform(df['product'])

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 338162 entries, 0 to 463290
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   session_id              338162 non-null  int64
 1   DateTime                338162 non-null  str
 2   user_id                 338162 non-null  int64
 3   product                 338162 non-null  int64
 4   campaign_id             338162 non-null  int64
 5   webpage_id              338162 non-null  int64
 6   product_category_1      338162 non-null  int64
 7   user_group_id           338162 non-null  float64
 8   gender                  338162 non-null  int64
 9   age_level               338162 non-null  float64
 10  user_depth              338162 non-null  float64
 11  city_development_index  338162 non-null  float64
 12  var_1                   338162 non-null  int64
 13  is_click                338162 non-null  int64
dtypes: float64(4), int64(9), str(1)
memory usage: 38.7 MB

In [17]:
df['DateTime'] = pd.to_datetime(df['DateTime'])
df['DateTime'] = df['DateTime'].dt.hour

In [18]:
df.head(2000).to_csv("dataset.csv", index=False)

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.nunique()

In [ ]:
print("not click：", df.loc[df['is_click']==0].shape[0])
print("clicked：", df.loc[df['is_click']==1].shape[0])

In [ ]:
labels = ['Not Click', 'Click'] 
size = df['is_click'].value_counts() 
colors = ['lightgreen', 'orange'] 
explode = [0, 0.1] 
plt.figure(figsize=(9,9)) 
plt.pie(size, colors=colors, explode=explode, labels=labels, shadow=True, autopct='%.2f%%') # 饼图参数设置
plt.axis('off') 
plt.title("Data Distribution") 
plt.legend()
plt.show()

In [ ]:
sns.heatmap(df.corr())
plt.show()

In [ ]:
sns.countplot(x='is_click', hue='gender',
              data=df, 
              palette='Set2')

# set the plot title and axis labels
plt.title('Click Counts by Gender')
plt.xlabel('Click')
plt.ylabel('Count')
plt.show()

In [ ]:
Male = df[df['gender']==1]
Male
Female = df[df['gender']==0]
print(f"Male click rate:{round(100*sum(Male['is_click']==1)/Male.shape[0],2)}%")
print(f"Female click rate:{round(100*sum(Female['is_click']==1)/Female.shape[0],2)}%")

In [ ]:
Is_clicked = df[df['is_click']==1]
Is_clicked_hour = Is_clicked.groupby('DateTime').agg('sum').reset_index()
Is_clicked_hour['is_click'] = 100*Is_clicked_hour['is_click']/sum(Is_clicked_hour['is_click'])
Is_clicked_hour

sns.lineplot(x='DateTime',
             y='is_click', 
             data=Is_clicked_hour, 
             palette='Set2')

plt.title('Click Counts by DateTime')
plt.xlabel('DateTime')
plt.ylabel('Count %')

plt.show()

In [ ]:
sns.countplot(x='product',data=df[df['is_click'] == 1], palette='Set2')

plt.title('Click Counts by Product')
plt.xlabel('Product_id')
plt.ylabel('Count')

plt.show()

In [ ]:
sns.countplot(y='campaign_id',data=df[df['is_click'] == 1], palette='Set2')

plt.title('Click Counts by Campaign_id')
plt.xlabel('Counts')
plt.ylabel('campaign_id')

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
df

In [ ]:
df_1 = df[df['is_click'] == 1].sample(n=7000, random_state=42)
df_0 = df[df['is_click'] == 0].sample(n=20000, random_state=42)

df_sampled = pd.concat([df_1, df_0]).sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
x_1 = df_sampled.drop(['is_click','session_id'],axis=1)
y_1 = df_sampled['is_click']
print('Clicked:',sum(y_1==1))
print('Not clicked:',sum(y_1==0))

In [ ]:
# df_2 = df.sample(n=30000)
# x_2 = df_2.drop(['is_click','session_id'],axis=1)
# y_2 = df_2['is_click']
# print('Clicked:',sum(y_2==1))
# print('Not clicked:',sum(y_2==0))
# x_2.shape

In [ ]:
# from imblearn.over_sampling import SMOTE
# from imblearn.under_sampling import RandomUnderSampler
# from imblearn.pipeline import Pipeline

# # over
# over = SMOTE(sampling_strategy=0.3)

# # under
# under = RandomUnderSampler(sampling_strategy=0.3)

# # pipeline
# steps = [('o', over),('u', under)]

# pipeline = Pipeline(steps=steps)

# x_2, y_2 = pipeline.fit_resample(x_2, y_2)

In [ ]:
# print(pd.Series(y_2).value_counts())
# x_2.shape

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_1 = scaler.fit_transform(x_1)
x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(x_1, y_1, test_size=0.3, shuffle=True)

In [ ]:
df_2 = df.sample(n=30000)
x_2 = df_2.drop(['is_click','session_id'],axis=1)
y_2 = df_2['is_click']
print('Clicked:',sum(y_2==1))
print('Not clicked:',sum(y_2==0))
x_2.shape

In [ ]:
x_2= scaler.fit_transform(x_2)
x_train_2, x_test_2, y_train_2, y_test_2 = train_test_split(x_2, y_2, test_size=0.3, shuffle=True)

In [ ]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
# over
# over = SMOTE(sampling_strategy=0.1)

# # under
# under = RandomUnderSampler(sampling_strategy=0.5)

# # pipeline
# steps = [('o', over),('u', under)]

# pipeline = Pipeline(steps=steps)

x_train_2, y_train_2 = sm.fit_resample(x_train_2, y_train_2)

In [ ]:
# pd.Series(y_train_1).value_counts()

In [ ]:
pd.Series(y_train_2).value_counts()

In [ ]:
pd.Series(y_test_2).value_counts()

In [ ]:
x_train_2.shape

In [ ]:
x_test_2.shape

In [ ]:
from sklearn.linear_model import LogisticRegression 
from sklearn.linear_model import SGDClassifier    
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.svm import SVC                      
from sklearn.tree import DecisionTreeClassifier     
from sklearn.ensemble import RandomForestClassifier 
from sklearn.model_selection import cross_val_score 
from sklearn.model_selection import GridSearchCV    

from sklearn.metrics import roc_auc_score, classification_report

from sklearn.ensemble import BaggingClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier                   

classifiers = {
    
    'LogisticRegression':LogisticRegression(),                               
    "KNN":KNeighborsClassifier(),              
    'DT':DecisionTreeClassifier(),             
    'RFC':RandomForestClassifier(),            
    'Bagging':BaggingClassifier(),             
    'SGD':SGDClassifier(),                     
    'GBC':GradientBoostingClassifier(),        
    'xgb':XGBClassifier()                      
}

In [ ]:
def accuracy_score(X_train, y_train):
    for key, classifier in classifiers.items():
        classifier.fit(X_train, y_train)
        training_score = cross_val_score(classifier, X_train, y_train, cv=5) 
        print("Classifier Name : ", classifier.__class__.__name__,"  Training Score ：", round(training_score.mean(), 2)*100,'%')

In [ ]:
accuracy_score(x_train_1, y_train_1)

In [ ]:
accuracy_score(x_train_2, y_train_2)

In [ ]:
def LR_gs(X_train, y_train):
    # LR
    LR_param = {
        'penalty':['l1', 'l2'],
        'C':[0.001, 0.01, 0.1, 1, 10]
    }

    LR_gs = GridSearchCV(LogisticRegression(),param_grid=LR_param, n_jobs=-1, scoring='accuracy')
    LR_gs.fit(X_train, y_train)

    LR_estimators = LR_gs.best_estimator_ 
    
    return LR_estimators
def KNN_gs(X_train, y_train):
    KNN_param = {
        'n_neighbors':list(range(2, 5, 1)),
        'algorithm':['auto','ball_tree','kd_tree','brute']
    }

    KNN_gs = GridSearchCV(KNeighborsClassifier(), param_grid=KNN_param, n_jobs=-1, scoring='accuracy')
    KNN_gs.fit(X_train, y_train)

    KNN_estimators = KNN_gs.best_estimator_ 
    
    return KNN_estimators
def SVC_gs(X_train, y_train):
    SVC_param = {
        'C':[0.5, 0.7, 0.9, 1],
        'kernel':['rfb', 'sigmod','poly']
    }

    SVC_gs = GridSearchCV(SVC(), param_grid=SVC_param, n_jobs=-1, scoring='accuracy')
    SVC_gs.fit(X_train, y_train)

    SVC_estimators = SVC_gs.best_estimator_ 
    
    return SVC_estimators
def DT_gs(X_train, y_train):
    DT_param = {
        'criterion':['gini', 'entropy'], 
        'max_depth':list(range(2, 5, 1)),
        'min_samples_leaf':list(range(3, 7, 1)) 
    }

    DT_gs = GridSearchCV(DecisionTreeClassifier(), param_grid=DT_param, n_jobs=-1, scoring='accuracy')
    DT_gs.fit(X_train, y_train)

    DT_estimators = DT_gs.best_estimator_ 
    
    return DT_estimators
def RFC_gs(X_train, y_train):
    RFC_param = {
        'n_estimators':[100, 150, 200], 
        'criterion':['gini', 'entropy'], 
        'max_depth':list(range(2,5,1)), 
    }
    
    RFC_gs = GridSearchCV(RandomForestClassifier(), param_grid=RFC_param, n_jobs=-1, scoring='accuracy')
    RFC_gs.fit(X_train, y_train)
    
    RFC_estimators = RFC_gs.best_estimator_
    
    return RFC_estimators
def BAG_gs(X_train, y_train):
    BAG_param = {
        'n_estimators':[10, 15, 20]
    }
    
    BAG_gs = GridSearchCV(BaggingClassifier(), param_grid=BAG_param, n_jobs=-1, scoring='accuracy')
    BAG_gs.fit(X_train, y_train)
    
    BAG_estimators = BAG_gs.best_estimator_
    
    return BAG_estimators
def SGD_gs(X_train, y_train):
    SGD_param = {
        'penalty':['l2','l1'],
        'max_iter':[1000, 1500, 2000]
    }
    
    SGD_gs = GridSearchCV(SGDClassifier(), param_grid=SGD_param, n_jobs=-1, scoring='accuracy')
    SGD_gs.fit(X_train, y_train)
    
    SGD_estimators = SGD_gs.best_estimator_
    
    return SGD_estimators
def XGB_gs(X_train, y_train):
    XGB_param = {
        'max_depth':[3,4,5,6]
    }
    
    XGB_gs = GridSearchCV(XGBClassifier(), param_grid=XGB_param, n_jobs=-1, scoring='accuracy')
    XGB_gs.fit(X_train, y_train)
    
    XGB_estimators = XGB_gs.best_estimator_
    
    return XGB_estimators

In [ ]:
LR_best_estimator = LR_gs(x_train_1,y_train_1)

KNN_best_estimator = KNN_gs(x_train_1,y_train_1)

SVC_best_estimator = SVC_gs(x_train_1,y_train_1)

DT_best_estimator = DT_gs(x_train_1,y_train_1)

RFC_best_estimator = RFC_gs(x_train_1,y_train_1)

BAG_best_estimator = BAG_gs(x_train_1,y_train_1)

SGD_best_estimator = SGD_gs(x_train_1,y_train_1)

In [ ]:
XGB_best_estimator = XGB_gs(x_train_1,y_train_1)

In [ ]:
LR_best_estimator = LR_gs(x_train_2,y_train_2)

KNN_best_estimator = KNN_gs(x_train_2,y_train_2)

SVC_best_estimator = SVC_gs(x_train_2,y_train_2)

DT_best_estimator = DT_gs(x_train_2,y_train_2)

RFC_best_estimator = RFC_gs(x_train_2,y_train_2)

BAG_best_estimator = BAG_gs(x_train_2,y_train_2)

SGD_best_estimator = SGD_gs(x_train_2,y_train_2)

XGB_best_estimator = XGB_gs(x_train_2,y_train_2)

In [ ]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score

result_df1 = pd.DataFrame(columns=['Accuracy', 'F1-score', 'Recall', 'Precision', 'AUC_ROC'],
                         index=['LR','KNN','DT','RFC','Bagging','SGD','XGB'])
def caculate(models, X_test, y_test):
 
    accuracy_results = []
    F1_score_results = []
    Recall_results = []
    Precision_results = []
    AUC_ROC_results = []
    
    for model in models:
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred) 
        precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)
        AUC_ROC = roc_auc_score(y_test, y_pred) # AUC
        
        
        accuracy_results.append(accuracy)
        F1_score_results.append(f1_score)
        Recall_results.append(recall)
        AUC_ROC_results.append(AUC_ROC)
        Precision_results.append(precision)
    return accuracy_results, F1_score_results, Recall_results, AUC_ROC_results, Precision_results
best_models = [LR_best_estimator, KNN_best_estimator, DT_best_estimator, RFC_best_estimator,
               BAG_best_estimator, SGD_best_estimator, XGB_best_estimator]
accuracy_results, F1_score_results, Recall_results, AUC_ROC_results, Precision_results = caculate(best_models,x_test_1,y_test_1)
result_df1['Accuracy'] = accuracy_results
result_df1['F1-score'] = F1_score_results
result_df1['Recall'] = Recall_results
result_df1['Precision'] = Precision_results
result_df1['AUC_ROC'] = AUC_ROC_results
result_df1

In [ ]:
best_models = [LR_best_estimator, KNN_best_estimator,  DT_best_estimator, RFC_best_estimator,
               BAG_best_estimator, SGD_best_estimator, XGB_best_estimator]
result_df2 = pd.DataFrame(columns=['Accuracy', 'F1-score', 'Recall', 'Precision', 'AUC_ROC'],
                         index=['LR','KNN','DT','RFC','Bagging','SGD','XGB'])
accuracy_results, F1_score_results, Recall_results, AUC_ROC_results, Precision_results = caculate(best_models,x_test_2,y_test_2)
result_df2['Accuracy'] = accuracy_results
result_df2['F1-score'] = F1_score_results
result_df2['Recall'] = Recall_results
result_df2['Precision'] = Precision_results
result_df2['AUC_ROC'] = AUC_ROC_results
result_df2

In [ ]:
sns.barplot(data=result_df1,x=result_df1.index,y='AUC_ROC')

In [ ]:
sns.barplot(data=result_df2,x=result_df2.index,y='AUC_ROC')

In [ ]:
top_3_classifier_1 = result_df1.sort_values('AUC_ROC',ascending = False)[:3]
top_3_classifier_1

In [ ]:
top_3_classifier_2 = result_df2.sort_values('AUC_ROC',ascending = False)[:3]
top_3_classifier_2

In [ ]:
from sklearn.ensemble import VotingClassifier

voting_clf1 = VotingClassifier(estimators=[('KNN', KNN_best_estimator), ('LR', LR_best_estimator), 
                                          ('SGD', SGD_best_estimator)], n_jobs=-1)

In [ ]:
voting_clf1.fit(x_train_1, y_train_1)

In [ ]:
voting_clf2 = VotingClassifier(estimators=[('DT', DT_best_estimator), ('SGD', SGD_best_estimator), 
                                          ('LR', LR_best_estimator)], n_jobs=-1)
voting_clf2.fit(x_train_2, y_train_2)

In [ ]:
y_final_pred = voting_clf1.predict(x_test_1)
print(classification_report(y_test_1, y_final_pred))

# Compute confusion matrix
confusion_mat = confusion_matrix(y_test_1, y_final_pred, labels=[1,0])
disp=ConfusionMatrixDisplay(confusion_matrix=confusion_mat,display_labels = ['Yes(1)','No(0)'])
disp.plot(cmap='Blues')
plt.show()
AUC_ROC = roc_auc_score(y_test_1, y_final_pred)
print(AUC_ROC)

In [ ]:
y_final_pred = voting_clf2.predict(x_test_2)
print(classification_report(y_test_2, y_final_pred))

# Compute confusion matrix
confusion_mat = confusion_matrix(y_test_2, y_final_pred, labels=[1,0])
disp=ConfusionMatrixDisplay(confusion_matrix=confusion_mat,display_labels = ['Yes(1)','No(0)'])
disp.plot(cmap='Blues')
plt.show()
AUC_ROC = roc_auc_score(y_test_2, y_final_pred)
print(AUC_ROC)

In [ ]:
df_3 = df.sample(n=100000)
x_3 = df_3.drop(['is_click','session_id'],axis=1)
y_3 = df_3['is_click']
print('Clicked:',sum(y_3==1))
print('Not clicked:',sum(y_3==0))
x_3.shape

In [ ]:
x_3= scaler.fit_transform(x_3)
x_train_3, x_test_3, y_train_3, y_test_3 = train_test_split(x_3, y_3, test_size=0.3, shuffle=True)

In [ ]:
x_train_3, y_train_3 = sm.fit_resample(x_train_3, y_train_3)

In [ ]:
pd.Series(y_train_3).value_counts()

In [ ]:
pd.Series(y_test_3).value_counts()

In [ ]:
x_train_3.shape

In [ ]:
x_test_3.shape

In [ ]:
LR_best_estimator = LR_gs(x_train_3,y_train_3)

In [ ]:
KNN_best_estimator = KNN_gs(x_train_3,y_train_3)

In [ ]:
BAG_best_estimator = BAG_gs(x_train_3,y_train_3)

In [ ]:
DT_best_estimator = DT_gs(x_train_3,y_train_3)

In [ ]:
SGD_best_estimator = SGD_gs(x_train_3,y_train_3)

In [ ]:
RFC_best_estimator = RFC_gs(x_train_3,y_train_3)

In [ ]:
XGB_best_estimator = XGB_gs(x_train_3,y_train_3)

In [ ]:
best_models = [LR_best_estimator, KNN_best_estimator,  DT_best_estimator, RFC_best_estimator,
               BAG_best_estimator, SGD_best_estimator, XGB_best_estimator]
result_df3 = pd.DataFrame(columns=['Accuracy', 'F1-score', 'Recall', 'Precision', 'AUC_ROC'],
                         index=['LR','KNN','DT','RFC','Bagging','SGD','XGB'])
accuracy_results, F1_score_results, Recall_results, AUC_ROC_results, Precision_results = caculate(best_models,x_test_3,y_test_3)
result_df3['Accuracy'] = accuracy_results
result_df3['F1-score'] = F1_score_results
result_df3['Recall'] = Recall_results
result_df3['Precision'] = Precision_results
result_df3['AUC_ROC'] = AUC_ROC_results
result_df3